project_id = "ywrgibkaacpqdhimswul"

[functions.flutterwave-initialize-payment]
verify_jwt = true

[functions.flutterwave-verify-payment]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false

[functions.flutterwave-payout]
verify_jwt = false

[functions.flutterwave-verify-account]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.get-user-emails]
verify_jwt = true

[functions.approve-task]
verify_jwt = true

[functions.approve-withdrawal]
verify_jwt = true

[functions.nin-approve]
verify_jwt = true

[functions.nin-reject]
verify_jwt = true

[functions.nin-status]
verify_jwt = true

[functions.submit-nin]
verify_jwt = true