project_id = "ywrgibkaacpqdhimswul"

[functions.flutterwave-initialize-payment]
verify_jwt = true

[functions.flutterwave-verify-payment]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true