// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-account.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-account.ts
var get_my_account_default = defineTool({
  name: "get_my_account",
  title: "Get my account",
  description: "Get the signed-in user's AdExchange profile, roles and wallet balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, roles, wallet] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId),
      supabase.from("wallets").select("balance, currency_type").eq("user_id", userId).maybeSingle()
    ]);
    const error = profile.error ?? roles.error ?? wallet.error;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const account = {
      email: ctx.getUserEmail(),
      profile: profile.data,
      roles: (roles.data ?? []).map((r) => r.role),
      wallet: wallet.data
    };
    return {
      content: [{ type: "text", text: JSON.stringify(account, null, 2) }],
      structuredContent: account
    };
  }
});

// src/lib/mcp/tools/list-campaigns.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_campaigns_default = defineTool2({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List AdExchange campaigns visible to the signed-in user (their own campaigns as an advertiser, or approved active campaigns available to promote).",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. 'active', 'paused', 'completed'."),
    limit: z.number().int().optional().describe("Max campaigns to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("campaigns").select("id, title, description, budget, payout, spent, status, approved, completed_tasks, created_at").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-campaign.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_campaign_default = defineTool3({
  name: "create_campaign",
  title: "Create campaign",
  description: "Create a new AdExchange campaign owned by the signed-in advertiser. Campaigns start unapproved and pending admin review.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Campaign title."),
    description: z2.string().trim().optional().describe("What promoters must do."),
    budget: z2.number().positive().describe("Total campaign budget."),
    payout: z2.number().positive().describe("Payout per completed task.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, budget, payout }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (payout > budget) {
      return {
        content: [{ type: "text", text: "Payout per task cannot exceed the total budget." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("campaigns").insert({
      advertiser_id: ctx.getUserId(),
      title,
      description: description ?? null,
      budget,
      payout,
      status: "pending"
    }).select("id, title, budget, payout, status, approved").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { campaign: data }
    };
  }
});

// src/lib/mcp/tools/list-my-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_tasks_default = defineTool4({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List promotion tasks claimed by the signed-in promoter, with their campaign and current status.",
  inputSchema: {
    status: z3.string().optional().describe("Optional status filter, e.g. 'claimed', 'submitted', 'approved', 'rejected'."),
    limit: z3.number().int().optional().describe("Max tasks to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("tasks").select(
      "id, status, claimed_at, submitted_at, reviewed_at, proof_url, rejection_reason, campaigns(id, title, payout)"
    ).eq("promoter_id", ctx.getUserId()).order("claimed_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool5({
  name: "list_transactions",
  title: "List wallet transactions",
  description: "List the signed-in user's wallet transactions (deposits, task payouts, withdrawals).",
  inputSchema: {
    limit: z4.number().int().optional().describe("Max transactions to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabase.from("transactions").select("*").order("created_at", { ascending: false }).limit(take);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ywrgibkaacpqdhimswul";
var mcp_default = defineMcp({
  name: "adexchange",
  title: "AdExchange",
  version: "0.1.0",
  instructions: "Tools for AdExchange, a marketplace connecting advertisers with promoters. Use `get_my_account` for the signed-in user's profile, roles and wallet, `list_campaigns` and `create_campaign` for advertiser campaigns, `list_my_tasks` for promoter tasks, and `list_transactions` for wallet activity. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_account_default,
    list_campaigns_default,
    create_campaign_default,
    list_my_tasks_default,
    list_transactions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
