// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywrgibkaacpqdhimswul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3cmdpYmthYWNwcWRoaW1zd3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMDMzNDAsImV4cCI6MjA3Nzc3OTM0MH0.qljbb6L1ZW-LOkeFgHSonunn4ya8UxnMGUe8Ox8IqpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});